<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
/*
    1. Create a function called "fetchPokemon" that returns 
       a Promise that resolves with the value :
       { data: {name: "Pickachu", power: 20} } after 2 seconds
    2. Print out "Program starting..."
    
    3. Create an async function that uses await to wait for
       the data to comes back from "fetchPokemon" then log out
       the data

    4. Call the async function you created
    5. Log out "Program complete!"

    After your're done the above ^:
    6. Change "fetchPokemon" to reject after 2 seconds instead
       with a new Error Object with the message "Danger, danger!"
    7. How can you modify your async function to catch this error?
*/
    //     function  fetchpokemon(){
    //         return new Promise((resolve,reject)=>{
    //             setTimeout(()=>{
    //                 var data=[{name:"Pickachu",power:69}];
    //                  if(data){
    //                      resolve(data);
    //                  }
    //                  else{
    //                     reject("Danger....");
    //              }
    //             },2000);
    //         });
    //     }
    //     console.log("Program Starts...");
    //   async  function handlepromise(){
    //         try{
    //           var data= await fetchpokemon();
    //           console.log(data);
    //         }
    //         catch(error){
    //             console.log(error);
    //         }
    //     }
        
    // handlepromise();
    // console.log("Program end...")



        function fetchPokemon(){
            return new Promise((resolve,reject)=>{
                setTimeout(()=>{
                    var data=[{name:"Pikachu", power:20}]
                    resolve(data);
                },2000)
            })
            }
            
        
        console.log("Program starting..");
        async function wait(){
          try{
            var x=await fetchPokemon();
            console.log(x);
          }catch(error){
            console.log(error);
          }
        }
        wait();
        console.log("Program Complete");

    </script>
</body>
</html>